name: Deploy to Staging
on:
  push:
    branches: [ main ]

jobs: 
  redeploy:
    name: Deploying everything to staging
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "${{ secrets.SSH_PRIVATEKEY }}" &> ~/ssh_key
          mkdir ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" &> ~/.ssh/known_hosts
          chmod 700 ~/ssh_key
          ssh -i ~/ssh_key root@139.59.57.59 -t "cd week-25-ci-next-app && git pull origin main && export PATH=/root/.nvm/versions/node/v22.14.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin && pnpm install && pnpm run build && pm2 restart fe-server && pm2 restart http-server && pm2 restart ws-server"
          
